// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1VsPIxjl4r7IcItYNgtWXm-VyQPLErsk',
    appId: '1:64359811466:web:565ebf59f58a27d395a073',
    messagingSenderId: '64359811466',
    projectId: 'projetoflutter-39dcb',
    authDomain: 'projetoflutter-39dcb.firebaseapp.com',
    databaseURL: 'https://projetoflutter-39dcb-default-rtdb.firebaseio.com',
    storageBucket: 'projetoflutter-39dcb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQqzMwmFIkg64KxsAP00fZaXafmy56J4w',
    appId: '1:64359811466:android:2d0f324c5920dea795a073',
    messagingSenderId: '64359811466',
    projectId: 'projetoflutter-39dcb',
    databaseURL: 'https://projetoflutter-39dcb-default-rtdb.firebaseio.com',
    storageBucket: 'projetoflutter-39dcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNTPPqHdsHQnPp3KJdF6jDNVOqQlU4Eos',
    appId: '1:64359811466:ios:8dd7e312b810e05895a073',
    messagingSenderId: '64359811466',
    projectId: 'projetoflutter-39dcb',
    databaseURL: 'https://projetoflutter-39dcb-default-rtdb.firebaseio.com',
    storageBucket: 'projetoflutter-39dcb.firebasestorage.app',
    iosClientId: '64359811466-0c97o8rdfbqk6dafrntsrhadmaqlkad0.apps.googleusercontent.com',
    iosBundleId: 'com.example.aula',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNTPPqHdsHQnPp3KJdF6jDNVOqQlU4Eos',
    appId: '1:64359811466:ios:8dd7e312b810e05895a073',
    messagingSenderId: '64359811466',
    projectId: 'projetoflutter-39dcb',
    databaseURL: 'https://projetoflutter-39dcb-default-rtdb.firebaseio.com',
    storageBucket: 'projetoflutter-39dcb.firebasestorage.app',
    iosClientId: '64359811466-0c97o8rdfbqk6dafrntsrhadmaqlkad0.apps.googleusercontent.com',
    iosBundleId: 'com.example.aula',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1VsPIxjl4r7IcItYNgtWXm-VyQPLErsk',
    appId: '1:64359811466:web:d05baa4e93ea412495a073',
    messagingSenderId: '64359811466',
    projectId: 'projetoflutter-39dcb',
    authDomain: 'projetoflutter-39dcb.firebaseapp.com',
    databaseURL: 'https://projetoflutter-39dcb-default-rtdb.firebaseio.com',
    storageBucket: 'projetoflutter-39dcb.firebasestorage.app',
  );
}
